apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../components/system-upgrade-controller
  - ../../../components/rancher
  - ../../../components/rancher-backup
  - ../../../components/weave-gitops