apiVersion: v1
kind: Secret
# type: Opaque
type: provisioning.cattle.io/cloud-credential
metadata:
    name: openstack-cloud-credential
    namespace: cattle-global-data
stringData:
    openstackcredentialConfig-password: ENC[AES256_GCM,data:oHKCgPXQ3eZf1ARHS0k=,iv:esUVLW1JXJGkKnpJCr+ociPhmdtvdlYNWDo5mMyLchc=,tag:IzrngZ8Kq60VtrawNx/hlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrvpu8z7cj5dtk5869vamdcv7n6tev4032dvuqgq3qzgrjqrm5rqw55j5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeXN4UC94ZXZpbm5GUklZ
            eWk5b09qRnAzblNwZVRLeC9vLzNPQU9WTXdzCnErVksyc29DMGhUNFo3QVRjei9l
            YTRKWVl1WDZnRlh3T0pDbE9lam1NdTgKLS0tIFNuMTgvRGFoOFBEV2UxRFhxUk04
            M3ExaHFYZVo4eTNjYjdibTFtZm9vK3MKicgn9UiU3WghXLffD4/PEjJb9HGs2tXa
            TFlk16yGqWUu9xv+puQgDy43DmNydC5gNOmDwDq/j5dPbHI7TKQvyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-01T18:07:56Z"
    mac: ENC[AES256_GCM,data:eVIuT4klVt6FUEixKxhkeVw7jHzMtfPc3IFBv3rb1soUZjHDakf4wW7jvthmp1AqrqmYN3l4ypps9jjwuG/9Gzt5d21FnO/p3O6w1LgrieFLiMxuqrX45VfBDyiznW6eJck+CjFVLPckWiBmKDby+drzTMH1FnyfN0duYOzpj5M=,iv:aCxt4qgGxg/YKytNwskdTtncy60L1MUTcrom6rMYrNA=,tag:TZObsSuqMYwtcldtHzfckA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
