# ensures that Openstack node driver is activated before trying to deploy workload clusters

apiVersion: management.cattle.io/v3
kind: NodeDriver
metadata:
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
  name: openstack
spec:
  active: true