apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  targetNamespace: cattle-system
  releaseName: rancher
  chart:
    spec:
      chart: rancher
      sourceRef:
        kind: HelmRepository
        name: rancher
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    hostname: rancher.k8s.arbutus
    replicas: 3
    bootstrapPassword: testPassword # TODO: Change and encrypt
    ingress:
      enabled: true