apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:VVy1+FizWKRWFLI/KFVlNojB67DxkGaQEy6v,iv:DE+nsG8PhhlPIJvNqQxsebh7s4fMulncicMZoKXmbEs=,tag:wnVnEhS9akFfkNoHUwaaKw==,type:str]
    CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:xxmgvrWFbI+70/j0vnRx7j8N88OxS9WoEaXeFZyDjkuAp0tlRg==,iv:1aR+oNla9i/kJ8m7JX0n7N7EDewP5qow1gIkZxrkyKo=,tag:0/7DP+gOZfv6l5WGWvfLSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zrvpu8z7cj5dtk5869vamdcv7n6tev4032dvuqgq3qzgrjqrm5rqw55j5e
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWQW9VRnJVaFE0YUhsQUdu
            Q1dqRk1OY25nSUtvM3dFNVowMnFVc0N5NWdrCjRmYWZYK0RMaHJ5Mzl1WkVYeXl1
            cXd3RVg4TFRIVW42L1AvcHJpMG45eUUKLS0tIHB3TC9TV21GWWhkNEx4bjRUSVNE
            VkRKVmwwVHNiS3gzaGRjekI0ODQ0TjQKXQRswSQZzSgOmlK0m78BHEKfBEX3424+
            w/IfhvtqMsCwPGQ2R1VIBrDFaL/0tWlw7FYall8/QTLd2ew/xWcfLg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-11-26T19:32:15Z"
    mac: ENC[AES256_GCM,data:az5j2h7prjQszCSZgZxDcDlhI/2QJIQDOjfrDgxZBG75riLrXwvrSB2riTPqeB7A/+ybsZduYyJOJ6il/yhbq3NYjjMrR+/UB/B6XW3eDaj7C9v3Qdyre6LU2e28/EvYNAQZTE4BrcAdrL2Agni18b9D3oimvmvRLO/lAz1g9CY=,iv:lpEzHlOfPGAQN16pGIeDpWO307m14NpKQgxVmbsLuxs=,tag:Ru7vKhL+th6njPvFGG9aDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.2
