apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system
resources:
  # - ../../base/config
  - cluster-config.yaml
  - cluster-secrets.sops.yaml
  - cloudflare-secrets.sops.yaml