apiVersion: batch/v1
kind: Job
metadata:
  {{ if .Release.IsInstall }}
  name: "{{ .Release.Name }}-post-install-wait"
  {{ else if .Release.IsUpgrade }}
  name: "{{ .Release.Name }}-post-upgrade-wait"
  {{ else }}
  name: "{{ .Release.Name }}-wait"
  {{ end }}

  namespace: cattle-system
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-cluster-wait"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      automountServiceAccountToken: true
      serviceAccountName: rancher
      containers:
      - name: wait-for-cluster
        image: bitnami/kubectl:latest
        command:
        - kubectl
        - -n fleet-default
        - wait
        - --for condition=ready
        - --timeout=-1s
        - clusters
        - {{ .Values.cluster.name }}