apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kured
  namespace: flux-system
spec:
  targetNamespace: kured
  releaseName: kured
  chart:
    spec:
      chart: kured
      sourceRef:
        kind: HelmRepository
        name: kured
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: -1
  values:
    configuration:
      # slackChannel: ""
      # slackHookUrl: ""
      # slackUsername: ""
      annotateNodes: true
    metrics:
      create: true
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8080"
    hostNetwork: false

    # service:
    #   port: 8081 # Kairos runs EdgeVPN on 8080