---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: kyverno-crds-source
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kyverno/kyverno.git
  ref:
    tag: v1.8.2
  ignore: |
    /*
    !/charts/kyverno/templates/crds.yaml
    !/charts/kyverno/Chart.yaml
    # exclude all
    # /charts/kyverno/templates/*
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno-crds
  namespace: flux-system
spec:
  targetNamespace: kyverno
  interval: 5m
  chart:
    spec:
      chart: charts/kyverno
      sourceRef:
        kind: GitRepository
        name: kyverno-crds-source
        namespace: flux-system