# h/t: https://github.com/Pumba98/flux2-gitops/tree/main/apps/all/system-upgrade-controller
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/rancher/system-upgrade-controller?ref=v0.9.1
images:
- name: rancher/system-upgrade-controller
  newTag: v0.9.1
patchesStrategicMerge:
# Delete namespace resource
- |
  $patch: delete
  apiVersion: v1
  kind: Namespace
  metadata:
    name: system-upgrade
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- server-plan.yaml
- agent-plan.yaml