apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-fleet-kubeconfigs
  annotations:
    policies.kyverno.io/title: Sync Fleet Kubeconfigs
    policies.kyverno.io/category: Rancher
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      This policy will synchronize kubeconfigs for Rancher-provisioned
      clusters to the flux-system namespace so that flux can bootstrap
      downstream clusters.
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: sync-fleet-kubeconfigs
    match:
        all:
        - resources:
            kinds:
            - provisioning.cattle.io/v1/Cluster
    exclude:
      any:
      - resources:
          namespaces:
          - fleet-local
    preconditions:
      all:
      - key: "{{ request.object.status.ready || false }}"
        operator: Equals
        value: true
      - key: "{{ request.object.status.clientSecretName || '' }}"
        operator: NotEquals
        value: ''
    generate:
      apiVersion: v1
      kind: Secret
      name: "{{ request.object.status.clientSecretName }}"
      namespace: flux-system
      synchronize: true
      clone:
        namespace: "{{request.object.metadata.namespace}}"
        name: "{{request.object.status.clientSecretName}}"