apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: sync-fleet-kubeconfigs
  annotations:
    policies.kyverno.io/title: Sync Fleet Kubeconfigs
    policies.kyverno.io/category: Rancher
    policies.kyverno.io/subject: Secret
    policies.kyverno.io/description: >-
      This policy will synchronize kubeconfigs for Rancher-provisioned
      clusters to the flux-system namespace so that flux can bootstrap
      downstream clusters.
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: sync-fleet-kubeconfigs
    match:
        all:
        - resources:
            kinds:
            - provisioning.cattle.io/v1/Cluster
    generate:
      apiVersion: v1
      kind: Secret
      name: "{{request.object.metadata.name}}-kubeconfig"
      namespace: flux-system # "{{request.object.metadata.name}}"
      synchronize: true
      clone:
        namespace: "{{request.object.metadata.namespace}}"
        name: "{{request.object.metadata.name}}-kubeconfig"