
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: flux-system
spec:
  targetNamespace: cnpg-system
  releaseName: cnpg
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: cnpg
        namespace: flux-system
  interval: 1h
  install:
    remediation:
      retries: -1

  values:
    crds:
      create: true